name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Memungkinkan trigger manual dari tab Actions

jobs:
  build:
    name: Build Flet APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Flet App to APK
        run: flet build apk

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/*.apk
